### PR TITLE
Commit to parse data from snulinks

### PR DESCRIPTION
**Pull request by Vutsuak16**
Check the Mess Json Folder . It has the python script to parse data from the webpage.
Covert it to JSON  and host it on the CDN

### CODE REVIEW

**Comment by arafsheikh** [comment]
Now that mess data is available online, directly fetch it from within the Android app. Why CDN?

**Comment by Vutsuak16** [comment]
Well i guess the web page can  easily be parsed using Python. Anyways the net has to be used atleast once , to retrieve data.. CDN would be a faster alternative for that

**Comment by Vutsuak16** [comment]
@mr-karan   just look at the latest commit 
The site has changed drastically , only one day menu is displayed on the web page .
Run the page and do the changes

**Comment by mr-karan** [comment]
Scraping from site is not a good idea : 
A) The menu is not available 24*7 

(image taken as of Jan7 2016 , 07:16)
screenshot from 2016-01-07 07-11-07

B) You would need to run the script _daily_ because the menu changes 

C) There's one method where we can write a script which fetches content directly from the website and displays it to users. However that would be much slower than our present CDN hosted JSON files. Performance hit. Ideally, I don't want that.

Have to keep with the original excel sheet only, unless the site gives us weekly data and is available 24*7

**Comment by arafsheikh** [comment]
Using a CDN in this case is irrelevant. The web app is on the university intranet resulting in extremely fast loading time.

I did some tests and here are the results:
- Loading time for `https://cdn.rawgit.com/mr-karan/SNUMessApp/master/MessJSON/DH1.json` : **0.875798 seconds**
- Loading time for `http://messmenu.snu.in/messMenu.php` : **0.015916 seconds**

That's a difference of about **55** times.

If you want to test it here's the python code:

``` python
from requests import get
print get("https://cdn.rawgit.com/mr-karan/SNUMessApp/master/MessJSON/DH1.json").elapsed.total_seconds() / get("http://messmenu.snu.in/messMenu.php").elapsed.total_seconds()
```

**Comment by rhnvrm** [comment]
Best would be to scrape from the android device directly and cache it on
the device and secondarily cache it online using the github api or
something similar, unless we can get our hands on the weekly mess menu from
the mess committee directly. Display a message if the person is not
connected to the university DNS or make a cache api which is hit after the
first person that day parses the messmenu php file and caches it for
others. Cacheing online is useful for people who are using their data packs
on their phone, i.e. walking towards the mess from the acad block or are
near georgia to choose where to eat.

**Comment by mr-karan** [comment]
But the key issue is to get the weekly data. No luck getting that.

**Comment by Vutsuak16** [comment]
@mr-karan  the only issue is getting the weekly data ,we can sort rest of the things later. If the site doesn't function properly we can do nothing.
I  think we need to talk to the mess commitee people

**Comment by arafsheikh** [comment]
Why do you want weekly data? The android app displays today's menu only.

Here is the chain of events:
- A user opens the android app
- If menu is available the app fetches today's menu (if not available displays an error)
- Pushes the retrieved data to us (as suggested by @rhnvrm)
- Now the mess website is the primary source of data and our server is the secondary one. If one goes down the android app switches its data source.

Completely eliminate the need of a person running a script every week(or everyday). Let the users do the work.

**Comment by arafsheikh** [comment]
Here is the code to fetch the menu from the android app. It uses `JSoup` parsing library.

``` Java
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.IOException;

public class temp {
  public static void main(String[] args) {
    try{
      Document page = Jsoup.connect("http://messmenu.snu.in/messMenu.php")
        .get();

      System.out.println("\nDH1 menu:\n");
      Element dh1 = page.getElementsByTag("tbody").get(0);
      Elements dh1_menu_items = dh1.getElementsByTag("p");
      System.out.println(dh1_menu_items.text());

      System.out.println("\nDH2 menu:\n");
      Element dh2 = page.getElementsByTag("tbody").get(1);
      Elements dh2_menu_items = dh2.getElementsByTag("p");
      System.out.println(dh2_menu_items.text());
    } catch(IOException e) {
      e.printStackTrace();
    }
  }
}
```

The output of the above code is:

```
DH1 menu:

 Butter Bread & Jam  Tea / Coffee  Sambhar  Idli  Green Salad  Mint Raita  Plain Rice  Rasam  Chapati  Mix Dal Tadka  Besan Gatta Currey  Murg Korma  Curd  Pulao  Sambhar  Chapati  Lobiya Chat Salad  Mutter Rassedar  Lauki Masala  Chicken Curry

DH2 menu:

 Toast,butter&jam  Bhaji  Puri  Tea/coffee  Lachcha Onion  Chutney   Rice  Sambhar  Aloo Jeera  Chapati  Fish Curry  Punjabi Kadhi  Finger Salad  Jeera Raita  Plain Rice  Dal Palak  Rasam  Chicken Curry  Chapati  Kofta Currey
```

This is just an example. We'll have to parse it better.

**Comment by arafsheikh** [comment]
If the above is okay I'll send a PR for the android app. Fine?

**Comment by mr-karan** [comment]
Alright

**Pull request merged**
