### PR TITLE
Fetch menu from snulinks web app

### PR DESCRIPTION
**Pull request by arafsheikh**
Fix #3 

Fully functional. 
Changed the `build.gradle` to support pre-Lollipop devices and updated the `buildToolsVersion`. If you try to build directly and run into errors then update build tools.

### CODE REVIEW

**Comment by mr-karan** [comment]
Great work @arafsheikh 

@Vutsuak16 Upload the new APK on Play Store

**Comment by Vutsuak16** [comment]
@arafsheikh  good work. I will see the apk once few dependencies issues are resolved on my Android Studio. I seem to be using api-21 

Just saw the apk , works well on my phone which is lollipop, Still need to see it on android level below 5

**Comment by arafsheikh** [comment]
Here is the debug apk file you can use to test the app:
https://www.dropbox.com/s/64jvf1re28emb8o/base.apk?dl=0

**Comment by Vutsuak16** [comment]
@arafsheikh  arrey i meant i need an android 4.4 phone to be fully sure :p

**Comment by Vutsuak16** [comment]
@arafsheikh  @mr-karan  published the update. Seems to work on all android versions

Will take some time to get processsed and be live on play store as the new version

**Comment by mr-karan** [comment]
Great

**Comment by Vutsuak16** [comment]
@arafsheikh  the app crashes when the mess menu is not uploaded .

**Pull request merged**
